### ISSUE TITLE
README.md should contain basic build/run instructions

### ISSUE THREAD

**Issue by audiodude** [mitmedialab/para#101]
I cloned the repository, and based on the presence of package.json, I thought to do `npm install` which is taking a long time. I can't tell if it's installing/compiling Redis or not.

Based on the presence of Gruntfile.js, I know I should do `grunt build` (from reading the Gruntfile). I'm not sure what I will do after that.

Is there a source of build instructions that is being maintained somewhere else?

**Comment by audiodude** [comment]
Okay so far what I've done is

`npm install`
`npm install -g bower`
`bower install`
`npm install -g grunt-cli`
`grunt install`

Now I'm trying `node server/app.js` as well as `cd server; node app.js` but both are failing with:

```
Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/ubuntu/para/server/app.js:6:18
    at Object.<anonymous> (/home/ubuntu/para/server/app.js:54:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

So I assume I need to create some config module? Is there documentation for _that_ somewhere?

**Comment by pixelmaid** [comment]
I added basic build instructions to README. Please note, the software is still in alpha..
